### ISSUE TITLE
"Leave me alone" marker

### ISSUE THREAD

**Issue by cstamas** [l2x6/pom-tuner#161]
Come up with some "standard", to leave element alone, like
```xml
<!-- pom-tuner: off -->
```

**Comment by ppalaga** [comment]
Off for what operations? All transformations? 
pom-tuner is a library potentially used by many Maven plugins or other tools. Should they all ignore the given element, regardless of their intents and purposes?

**Comment by cstamas** [comment]
@ppalaga sorry, all these issues were created hastily by me. You are right, this is a "low level" lib. I will pull something a top of it in toolbox.
