### ISSUE TITLE
Transformation feedback

### ISSUE THREAD

**Issue by cstamas** [l2x6/pom-tuner#163]
Transformation should be able to provide some feedback, like "leave me alone element found; cannot apply". Or "property to update not found; probably inherited" (from parent POM external to reactor).

**Comment by ppalaga** [comment]
Wouldn't those be exceptions to throw?

If `Transformation.perform()` would return some kind of result value, what would you do with it (other than log or make the whole program fail)?

**Comment by cstamas** [comment]
@ppalaga sorry, all these issues were created hastily by me. You are right, this is a "low level" lib. I will pull something a top of it in toolbox.

**Comment by ppalaga** [comment]
Maybe your intention was to be able to build complex Transformation pipelines by composing existing Transformers? 

Something like the following?

```java
Tune.file("pom.xml")
    .if(not(hasProperty("foo.bar")))
    .then(addProperty("foo.bar"))
    .endif()
    .save();
```

Where `addProperty()` would be an existing Transformer and `if()`, `then()` else would be parts of a new transformer DSL that we would have to add?
